***Introduction to Tensors***

A tensor is a basic data structure in Mindspore network computing.

*Step 1 : Create a tensor using an array*

In [1]:
#Import Mindspore
import mindspore

#The cell outputs multiple lines at the same time.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np
from mindspore import Tensor
from mindspore import dtype

#Use an array to create a tensor
x = Tensor(np.array([[1, 2], [3, 4]]), dtype.int32)
x

Tensor(shape=[2, 2], dtype=Int32, value=
[[1, 2],
 [3, 4]])

*Step 2 : Create tensors using numbers*

In [2]:
#Use a number to create tensors
y = Tensor(1.0, dtype.int32)
z = Tensor(2, dtype.int32)
y
z

Tensor(shape=[], dtype=Int32, value= 1)

Tensor(shape=[], dtype=Int32, value= 2)

*Step 3 : Create a tensor using Boolean*

In [3]:
#Use Boolean to create a tensor
m = Tensor(True, dtype.bool_)
m

Tensor(shape=[], dtype=Bool, value= True)

*Step 4 : Create a tensor using a tuple*

In [4]:
#Use a tuple to create a tensor
n = Tensor((1, 2, 3), dtype.int16)
n

Tensor(shape=[3], dtype=Int16, value= [1, 2, 3])

*Step 5 : Create a tensor using a list*

In [5]:
#Use a list to create a tensor
p = Tensor([4.0, 5.0, 6.0], dtype.float64)
p

Tensor(shape=[3], dtype=Float64, value= [ 4.00000000e+00,  5.00000000e+00,  6.00000000e+00])

*Step 6 : Inherit attributes of another tensor to form a new tensor*

In [6]:
from mindspore import ops
oneslike = ops.OnesLike()
x = Tensor(np.array([[0, 1], [2, 1]]).astype(np.int32))
output = oneslike(x)
output

Tensor(shape=[2, 2], dtype=Int32, value=
[[1, 1],
 [1, 1]])

*Step 7 : Output constant tensor value*

In [7]:
from mindspore.ops import operations as ops

shape = (2, 2)
ones = ops.Ones()
output = ones(shape, dtype.float32)
print(output)

zeros = ops.Zeros()
output = zeros(shape, dtype.float32)
print(output)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


**Tensor Attributes**

Tensor attributes include shape and data type(dtype)
- Shape : a tuple
- Data type : a data type of mindspore

In [8]:
x = Tensor(np.array([[1, 2], [3, 4]]) , dtype.int32)

x.shape   #Shape
x.dtype   #Data type
x.ndim    #Dimension
x.size    #Size

(2, 2)

mindspore.int32

2

4

**Tensor Methods**

asnumpy(): Converts a tensor to an array of NumPy

In [9]:
y = Tensor(np.array([[True, True], [False, False]]), dtype.bool_)

#Convert the tensor data type to NumPy
y_array = y.asnumpy()

y
y_array

Tensor(shape=[2, 2], dtype=Bool, value=
[[ True,  True],
 [False, False]])

array([[ True,  True],
       [False, False]])

**Tensor Operations**

There are many operations between tensors, including arithmetic, linear algebra, matrix processing (transposing, indexing, and slicing), and sampling.
<br>The following describes several operations. The usage of tensor computation is similar to that NumPy

*Step 1 : Perform indexing and slicing*

In [11]:
tensor = Tensor(np.array([[0, 1], [2, 3]]).astype(np.float32))

print("First row: {}".format(tensor[0]))
print("First column: {}".format(tensor[:, 0]))
print("Last row: {}".format(tensor[..., -1]))

First row: [0. 1.]
First column: [0. 2.]
Last row: [1. 3.]


*Step 2 : Concatenate tensors*

In [13]:
data1 = Tensor(np.array([[0, 1], [2, 3]]).astype(np.float32))
data2 = Tensor(np.array([[4, 5], [6, 7]]).astype(np.float32))

op = ops.Stack()
output = op([data1, data2])
print(output)

[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]


*Step 3 : Convert to NumPy*

In [16]:
zeros = ops.Zeros()
output = zeros((2, 2), dtype.float32)
print("output: {}".format(type(output)))
n_output = output.asnumpy()
print("n_output:{}".format(type(n_output)))

output: <class 'mindspore.common._stub_tensor.StubTensor'>
n_output:<class 'numpy.ndarray'>
